vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        TeamMember:
            uri_prefix: /attchments/imagesMembers
            upload_destination: '%kernel.project_dir%/public/attchments/imagesMembers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
